#!/bin/bash

# forked from https://gist.github.com/brandonprry/4305328f069f7a951ccc/3717cb1d04c715b9ae1e1edf1662bae138adda91

cores=$1
inputdir=$2
outputdir=$3
command=$4
params=${@:5}
pids=""
total=`ls $inputdir | wc -l`

for k in `seq 1 $cores $total`
do
	for i in `seq 0 $(expr $cores - 1)`
	do
		file=`ls -Sr $inputdir | sed $(expr $i + $k)"q;d"`
		afl-tmin -i $inputdir/$file -o $outputdir/$file $params -- $4 &
	done

	wait
done
